AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Load balancing stack template for
  AWS CloudFormation 

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The subnets that the load balancer will span

  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id 
    Description: The security group that will be attached to the instance

Resources:
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets: !Ref Subnets
      IpAddressType: ipv4

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 443
      Protocol: HTTPS
      Matcher:
        HttpCode: 200
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: '/'
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 3
      TargetGroupAttributes:
        - 
          Key: 'deregistration_delay.timeout_seconds'
          Value: 10

  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref NetworkLoadBalancer
      Port: 443
      Protocol: HTTPS
      DefaultActions:
        - 
          TargetGroupArn: !Ref TargetGroup
          Type: forward

Outputs:
  LoadBalancerDNSName:
    Description: DNS name of the application load balancer
    Value: !GetAtt NetworkLoadBalancer.DNSName

  TargetGroupARN:
    Description: ARN of the load balancer target group
    Value: !Ref TargetGroup